services:
  Lumina-PDF:
    image: lumina-pdf:ultra-lite
    build:
      context: ../..
      dockerfile: docker/embedded/Dockerfile.ultra-lite
    container_name: Lumina-PDF-ultra-lite
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080$${SYSTEM_ROOTURIPATH:-''}/api/v1/info/status | grep -q 'UP'"]
      interval: 5s
      timeout: 10s
      retries: 16
    ports:
      - "8080:8080"
    volumes:
      - ../../LUMINA/latest/config:/configs:rw
      - ../../LUMINA/latest/logs:/logs:rw
    environment:
      DISABLE_ADDITIONAL_FEATURES: "true"
      SECURITY_ENABLELOGIN: "false"
      ENDPOINTS_GROUPS_TO_REMOVE: "CLI"
      LANGS: "en_GB,en_US"
      SYSTEM_DEFAULTLOCALE: en-US
      UI_APPNAME: Lumina-PDF
      UI_HOMEDESCRIPTION: Ultra-lite version of Lumina-PDF
      UI_APPNAMENAVBAR: Lumina-PDF Ultra-lite
      SYSTEM_MAXFILESIZE: "50"
    networks:
      - LUMINA-network

networks:
  LUMINA-network:
    driver: bridge
